# Base configs
#baseurl: "https://photography.impswrld.xyz"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Í©ú ImpsWRLD - Œµ(¬¥ÔΩ°‚Ä¢·éë‚Ä¢`)„Å£ üíï"
subtitle: "It is all a lense, here's my perspecitve."
author: "Takunda Marowa"
header:
  title: "Visuals"
  subtitle: "by imp3tuz"
footer:
  name: "Hey there, my name is Taku (imp)"
  bio: "I am a multidisciplinary artist from Zimbabwe. You'll find me making video games for the most part, but the beauty about me fascinates me. This is a wall for me to splash my visual paint. Be kind, enjoy."
  github: 'Shout out to AJ for this. If you wanna replicate this, peep- <a href="https://github.com/ramswaroop/photography">on github</a> ;)'
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
#exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/imp3tuz0_0"
  github: "https://www.github.com/iamTakuu"
